/**
 * packingDB.js — Requisitos de viaje y sugerencias de equipaje por país
 * Cobertura global — optimizado para viajeros hispanohablantes
 */

export const COUNTRY_REQUIREMENTS = {

  // EUROPA
  'España': { visa: { needed: false, info: 'Estás en casa.' }, adapter: { needed: false, info: 'Tipo C/F — estándar europeo.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['El 112 funciona en toda España.'], emergency: '112' },
  'Francia': { visa: { needed: false, info: 'Schengen — libre circulación para ciudadanos de la UE.' }, adapter: { needed: false, info: 'Tipo C/E — compatible con enchufes españoles.' }, currency: { info: 'Euro. Tarjeta aceptada en casi todo.' }, vaccines: [], tips: ['El TGV conecta ciudades principales muy rápido.', 'Muchos museos en París tienen día gratuito.'], emergency: '112 · 17 (policía) · 15 (SAMU)' },
  'Italia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F/L — enchufes españoles funcionan.' }, currency: { info: 'Euro. Lleva efectivo para zonas turísticas.' }, vaccines: [], tips: ['Reserva el Vaticano y la Uffizi con antelación.', 'Valida siempre el billete de tren.'], emergency: '112 · 118 (ambulancia) · 113 (policía)' },
  'Portugal': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F — igual que España.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['Cuidado con carteristas en los tranvías de Lisboa.'], emergency: '112' },
  'Alemania': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Euro. El efectivo sigue siendo muy usado en Alemania.' }, vaccines: [], tips: ['Muchos establecimientos solo aceptan efectivo.'], emergency: '112 · 110 (policía)' },
  'Reino Unido': { visa: { needed: false, info: 'Sin visado hasta 6 meses. Puede requerir ETA — verifica en gov.uk.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador imprescindible.' }, currency: { info: 'Libra esterlina (GBP). Tarjeta ampliamente aceptada.' }, vaccines: [], tips: ['Circulación por la izquierda.', 'Oyster Card para transporte en Londres.'], emergency: '999 · 112' },
  'Países Bajos': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['Cuidado con los carriles bici en Amsterdam.'], emergency: '112' },
  'Bélgica': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/E.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['Bruselas es sede de la UE — controles de seguridad frecuentes.'], emergency: '112 · 101 (policía) · 100 (ambulancia)' },
  'Suiza': { visa: { needed: false, info: 'Sin visado para europeos (no UE pero Schengen).' }, adapter: { needed: true, type: 'Tipo J', info: 'Suiza tiene su propio enchufe. Adaptador necesario.' }, currency: { info: 'Franco suizo (CHF). Todo es muy caro — presupuesta el doble.' }, vaccines: [], tips: ['Transporte público impecable.', 'Swiss Travel Pass si usas mucho el tren.'], emergency: '112 · 117 (policía) · 144 (ambulancia)' },
  'Austria': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['Viena City Card merece la pena.'], emergency: '112 · 133 (policía) · 144 (ambulancia)' },
  'Grecia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro. En islas pequeñas lleva efectivo.' }, vaccines: [], tips: ['En verano el calor es extremo.', 'Reserva ferrys entre islas con antelación.'], emergency: '112 · 100 (policía) · 166 (ambulancia)' },
  'Turquía': { visa: { needed: true, info: 'E-Visa para españoles: aprox 50 USD. Tramitar en evisa.gov.tr antes de viajar.' }, adapter: { needed: false, info: 'Tipo C/F — compatible con enchufes españoles.' }, currency: { info: 'Lira turca (TRY). Mejor cambiar allí.' }, vaccines: [], tips: ['El Gran Bazar cierra domingos.', 'Negocia precios en mercados.'], emergency: '112 · 155 (policía)' },
  'República Checa': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/E.' }, currency: { info: 'Corona checa (CZK). No usan euro.' }, vaccines: [], tips: ['Praga muy concurrida en temporada alta — reserva con antelación.'], emergency: '112 · 158 (policía) · 155 (ambulancia)' },
  'Hungría': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Forinto húngaro (HUF). No usan euro.' }, vaccines: [], tips: ['Budapest es muy asequible.'], emergency: '112 · 107 (policía) · 104 (ambulancia)' },
  'Polonia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/E.' }, currency: { info: 'Esloti polaco (PLN). No usan euro.' }, vaccines: [], tips: ['Cracovia y Varsovia son asequibles.'], emergency: '112 · 997 (policía) · 999 (ambulancia)' },
  'Noruega': { visa: { needed: false, info: 'Schengen (no UE).' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Corona noruega (NOK). Uno de los países más caros del mundo.' }, vaccines: [], tips: ['Todo con tarjeta — apenas se usa efectivo.', 'Ferrys para fiordos: reserva con semanas de antelación.'], emergency: '112 · 02800 (policía) · 113 (ambulancia)' },
  'Suecia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Corona sueca (SEK). País prácticamente cashless.' }, vaccines: [], tips: ['Muchos museos en Estocolmo son gratuitos.'], emergency: '112' },
  'Dinamarca': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F/K.' }, currency: { info: 'Corona danesa (DKK). No usan euro.' }, vaccines: [], tips: ['Copenhague es muy ciclista — alquila una bici.'], emergency: '112' },
  'Irlanda': { visa: { needed: false, info: 'Sin visado para españoles. No es Schengen pero sin visado.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas como UK. Adaptador necesario.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['El clima es muy cambiante — lleva siempre impermeable.'], emergency: '112 · 999' },
  'Croacia': { visa: { needed: false, info: 'Schengen desde 2023.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (desde enero 2023).' }, vaccines: [], tips: ['Islas del Adriático: reserva ferrys en verano.'], emergency: '112 · 192 (policía) · 194 (ambulancia)' },
  'Eslovenia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro.' }, vaccines: [], tips: ['Ljubljana es muy pequeña y caminable.', 'El lago Bled es impresionante pero muy concurrido.'], emergency: '112 · 113 (policía)' },
  'Serbia': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. No es Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Dinar serbio (RSD). Efectivo principalmente.' }, vaccines: [], tips: ['Belgrado tiene vida nocturna increíble.'], emergency: '112 · 192 (policía) · 194 (ambulancia)' },

  // ASIA
  'Japón': { visa: { needed: false, info: 'Sin visado para españoles y la mayoría de latinoamericanos hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A', info: 'Dos clavijas planas. Adaptador necesario.' }, currency: { info: 'Yen (JPY). El efectivo es imprescindible — muchos locales no aceptan tarjeta.' }, vaccines: [], tips: ['Suica/Pasmo card para el transporte.', 'Compra SIM de datos en el aeropuerto.', 'JR Pass: actívalo el primer día de uso.'], emergency: '110 (policía) · 119 (ambulancia)' },
  'Tailandia': { visa: { needed: false, info: 'Sin visado para españoles hasta 60 días. Latinoamericanos verificar.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Varios tipos. Adaptador universal recomendado.' }, currency: { info: 'Baht (THB). Los cajeros cobran comisión alta (220 THB). Lleva efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Usa Grab en vez de taxis de calle.', 'No bebas agua del grifo.', 'Ropa que cubra para templos.'], emergency: '191 (policía) · 1669 (ambulancia)' },
  'Vietnam': { visa: { needed: true, info: 'E-visa: 25 USD, válida 90 días. En evisa.xuatnhapcanh.gov.vn.' }, adapter: { needed: true, type: 'Tipo A/C', info: 'Adaptador recomendado.' }, currency: { info: 'Dong (VND). Solo efectivo. 1€ ≈ 26.000 VND.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Usa Grab para transporte.', 'Cruza la calle despacio y sin parar.'], emergency: '113 (policía) · 115 (ambulancia)' },
  'Indonesia': { visa: { needed: true, info: 'Visa on Arrival en aeropuertos principales: 35 USD por 30 días.' }, adapter: { needed: false, info: 'Tipo C/F — compatible con enchufes europeos.' }, currency: { info: 'Rupia (IDR). Efectivo en zonas fuera de centros turísticos.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Repelente de mosquitos esencial.', 'En Bali, respeta las ceremonias.'], emergency: '110 (policía) · 118 (ambulancia)' },
  'India': { visa: { needed: true, info: 'E-Visa obligatoria: 25-80 USD. En indianvisaonline.gov.in — al menos 4 días de antelación.' }, adapter: { needed: true, type: 'Tipo C/D/M', info: 'Varios tipos. Adaptador universal necesario.' }, currency: { info: 'Rupia (INR). Efectivo necesario fuera de ciudades grandes.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }, { name: 'Rabia', priority: 'considerar' }], tips: ['Solo agua embotellada.', 'Lleva papel higiénico propio.', 'Seguro médico con cobertura alta.'], emergency: '100 (policía) · 102 (ambulancia)' },
  'China': { visa: { needed: true, info: 'Visado requerido. Transit visa-free 72/144h en algunas ciudades. Consulta el consulado.' }, adapter: { needed: true, type: 'Tipo A/C/I', info: 'Varios tipos. Adaptador universal recomendado.' }, currency: { info: 'Yuan (CNY). Alipay y WeChat Pay imprescindibles — descarga las apps antes de llegar.' }, vaccines: [], tips: ['Google/WhatsApp/Instagram no funcionan — instala VPN antes de entrar.', 'WeChat es esencial.'], emergency: '110 (policía) · 120 (ambulancia)' },
  'Corea del Sur': { visa: { needed: false, info: 'Sin visado para españoles y la mayoría de latinoamericanos hasta 90 días.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Won (KRW). Tarjeta aceptada en casi todo.' }, vaccines: [], tips: ['Usa Kakao Maps — Google Maps no funciona bien en Corea.', 'T-Money card para transporte.'], emergency: '112 (policía) · 119 (ambulancia)' },
  'Singapur': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos hasta 30-90 días.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Dólar singapurense (SGD). Tarjeta aceptada en todo.' }, vaccines: [], tips: ['Hawker Centers para comer barato.', 'MRT eficiente y económico.'], emergency: '999 (policía) · 995 (ambulancia)' },
  'Camboya': { visa: { needed: true, info: 'E-visa en evisa.gov.kh: 36 USD. También visa on arrival.' }, adapter: { needed: true, type: 'Tipo A/C/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'USD ampliamente aceptado. El riel (KHR) también circula.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Angkor Wat: cubrir hombros y rodillas.', 'No bebas agua del grifo.'], emergency: '117 (policía) · 119 (ambulancia)' },
  'Filipinas': { visa: { needed: false, info: 'Sin visado para españoles hasta 30 días (ampliable).' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Peso filipino (PHP). Efectivo muy usado fuera de Manila.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Temporada de tifones: junio-noviembre.'], emergency: '911' },
  'Nepal': { visa: { needed: true, info: 'Visa on Arrival en Katmandú: 30 USD (15 días) o 50 USD (30 días).' }, adapter: { needed: true, type: 'Tipo C/D/M', info: 'Adaptador universal necesario.' }, currency: { info: 'Rupia nepalesa (NPR). Solo efectivo en zonas de trekking.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Rabia', priority: 'recomendada' }], tips: ['Aclimatarse despacio para el mal de altura.', 'Lleva mucho efectivo para el Himalaya.'], emergency: '100 (policía) · 102 (ambulancia)' },
  'Sri Lanka': { visa: { needed: true, info: 'ETA online obligatoria: 20 USD. En eta.gov.lk.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Tipo D y G. Adaptador necesario.' }, currency: { info: 'Rupia de Sri Lanka (LKR). Efectivo necesario.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Ropa respetuosa para templos.', 'Malaria en algunas zonas — consultar.'], emergency: '119 (policía) · 110 (ambulancia)' },

  // ORIENTE MEDIO
  'Emiratos Árabes Unidos': { visa: { needed: false, info: 'Sin visado para españoles y muchos latinoamericanos hasta 30-90 días.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Dírham (AED). Tarjeta aceptada en todo.' }, vaccines: [], tips: ['Ropa respetuosa en zonas públicas y mezquitas.', 'Alcohol solo en hoteles y zonas específicas.'], emergency: '999 (policía) · 998 (ambulancia)' },
  'Israel': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días.' }, adapter: { needed: true, type: 'Tipo H', info: 'Israel tiene su propio enchufe tipo H. Adaptador necesario.' }, currency: { info: 'Séquel (ILS). Tarjeta aceptada en casi todo.' }, vaccines: [], tips: ['Consulta siempre el Ministerio de AAEE antes de viajar.'], emergency: '100 (policía) · 101 (ambulancia)' },
  'Jordania': { visa: { needed: true, info: 'Visa on Arrival: 40 JOD. Jordan Pass incluye visa + Petra.' }, adapter: { needed: true, type: 'Tipo C/D/G', info: 'Adaptador universal recomendado.' }, currency: { info: 'Dinar jordano (JOD). Efectivo fuera de Amán.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Jordan Pass es la mejor opción si visitas Petra.'], emergency: '911' },

  // ÁFRICA
  'Marruecos': { visa: { needed: false, info: 'Sin visado para españoles y latinoamericanos hasta 90 días.' }, adapter: { needed: false, info: 'Tipo C/E — compatible con enchufes españoles.' }, currency: { info: 'Dírham (MAD). No se puede sacar del país. Efectivo necesario en zocos.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Negocia siempre precios en zocos.', 'No bebas agua del grifo.', 'Ropa respetuosa en zonas conservadoras.'], emergency: '190 (policía) · 150 (ambulancia)' },
  'Egipto': { visa: { needed: true, info: 'E-visa en visa2egypt.gov.eg: 25 USD. También visa on arrival.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Libra egipcia (EGP). Efectivo muy necesario.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['No bebas agua del grifo.', 'Las propinas (baksheesh) son muy comunes.'], emergency: '122 (policía) · 123 (ambulancia)' },
  'Sudáfrica': { visa: { needed: false, info: 'Sin visado para españoles hasta 30 días. Latinoamericanos verificar.' }, adapter: { needed: true, type: 'Tipo M', info: 'Tipo M — tres clavijas redondas grandes. Adaptador necesario.' }, currency: { info: 'Rand (ZAR). Tarjeta en zonas urbanas.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida si vienes de zona endémica' }], tips: ['No camines solo de noche.', 'Uber es económico y seguro.'], emergency: '10111 (policía) · 10177 (ambulancia)' },
  'Kenia': { visa: { needed: true, info: 'E-visa obligatoria: 50 USD. En evisa.go.ke.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Chelín keniano (KES). Efectivo fuera de Nairobi.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Malaria endémica — toma profilaxis.', 'Safari Masai Mara: julio-octubre.'], emergency: '999 · 112' },
  'Tanzania': { visa: { needed: true, info: 'E-visa: 50 USD. En visa.immigration.go.tz.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Adaptador necesario.' }, currency: { info: 'Chelín tanzano (TZS). Efectivo muy necesario.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Malaria endémica — profilaxis obligatoria.', 'Zanzíbar: ropa respetuosa en ciudad.'], emergency: '112 · 115 (policía)' },
  'Etiopía': { visa: { needed: true, info: 'E-visa disponible en evisa.et: 52 USD.' }, adapter: { needed: true, type: 'Tipo C/F/L', info: 'Adaptador universal recomendado.' }, currency: { info: 'Birr (ETB). Solo efectivo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['No bebas agua del grifo.', 'Addis Abeba está a 2.355m — posible mal de altura.'], emergency: '991 (policía) · 907 (ambulancia)' },

  // AMÉRICAS
  'Estados Unidos': { visa: { needed: true, info: 'ESTA para españoles: 21 USD en esta.cbp.dhs.gov. Latinoamericanos necesitan visa B1/B2.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas planas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Dólar (USD). Propina del 15-20% obligatoria.' }, vaccines: [], tips: ['Seguro médico imprescindible — la sanidad es carísima.', 'Tip obligatorio en restaurantes y servicios.'], emergency: '911' },
  'Canadá': { visa: { needed: true, info: 'ETA para europeos: 7 CAD en canada.ca/eta. Latinoamericanos suelen necesitar visa.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Mismo que EEUU. Adaptador necesario.' }, currency: { info: 'Dólar canadiense (CAD). Propina del 15-18%.' }, vaccines: [], tips: ['En invierno temperaturas extremas — ropa técnica obligatoria.'], emergency: '911' },
  'México': { visa: { needed: false, info: 'Sin visado para españoles y europeos hasta 180 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas planas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Peso mexicano (MXN). Efectivo en mercados y zonas rurales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Usa Uber — más seguro que taxis de calle.', 'No bebas agua del grifo.'], emergency: '911' },
  'Colombia': { visa: { needed: false, info: 'Sin visado para europeos y la mayoría de latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas planas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Peso colombiano (COP). Efectivo fuera de centros urbanos.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada (zonas selváticas)' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Usa InDriver o Uber.', 'Precaución nocturna en zonas desconocidas.'], emergency: '123' },
  'Argentina': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tres clavijas en triángulo. Adaptador necesario.' }, currency: { info: 'Peso argentino (ARS). Economía compleja — infórmate del tipo de cambio.' }, vaccines: [], tips: ['La Patagonia requiere planificación — distancias enormes.'], emergency: '911' },
  'Chile': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: false, info: 'Tipo C/L — compatible con enchufes españoles.' }, currency: { info: 'Peso chileno (CLP). Tarjeta aceptada en ciudades.' }, vaccines: [], tips: ['Atacama: protección solar extrema.', 'Vuelos internos necesarios para cubrir el país.'], emergency: '133 (policía) · 131 (ambulancia)' },
  'Perú': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Varios tipos. Adaptador recomendado.' }, currency: { info: 'Sol (PEN). Efectivo en Cusco y Machu Picchu.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada (Amazonas)' }], tips: ['Cusco a 3.400m — aclimatarse 2 días.', 'Tren a Machu Picchu: reserva con meses de antelación.'], emergency: '105 (policía) · 117 (ambulancia)' },
  'Brasil': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días.' }, adapter: { needed: true, type: 'Tipo N', info: 'Tipo N — similar al C pero patillas más gruesas. Adaptador recomendado.' }, currency: { info: 'Real (BRL). Efectivo en playas y locales pequeños.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['No muestres móvil o joyas en la calle.', 'Uber muy popular y seguro.'], emergency: '190 (policía) · 192 (ambulancia)' },
  'Ecuador': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Dólar americano (USD) — Ecuador lo usa desde 2000.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada (Amazonas)' }], tips: ['Quito a 2.850m — posible mal de altura.', 'Galápagos: permisos y reserva con mucha antelación.'], emergency: '911' },
  'Bolivia': { visa: { needed: false, info: 'Sin visado para europeos y la mayoría de latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/C', info: 'Adaptador recomendado.' }, currency: { info: 'Boliviano (BOB). Efectivo principalmente.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada (zonas tropicales)' }], tips: ['La Paz a 3.600m — aclimatación obligatoria.', 'Salar de Uyuni: impresionante en época de lluvia.'], emergency: '110 (policía) · 118 (ambulancia)' },
  'Uruguay': { visa: { needed: false, info: 'Sin visado.' }, adapter: { needed: true, type: 'Tipo C/F/L', info: 'Uruguay usa tipo L. Adaptador recomendado.' }, currency: { info: 'Peso uruguayo (UYU). Tarjeta ampliamente aceptada.' }, vaccines: [], tips: ['Uno de los países más seguros de Sudamérica.'], emergency: '911' },
  'Paraguay': { visa: { needed: false, info: 'Sin visado.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Adaptador recomendado.' }, currency: { info: 'Guaraní (PYG). Efectivo principalmente.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Ciudad del Este: zona de compras con precios muy bajos.'], emergency: '911' },
  'Venezuela': { visa: { needed: false, info: 'Sin visado para europeos. Consulta el Ministerio de AAEE antes de viajar.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Bolívar (VES). El USD es ampliamente aceptado.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Consulta siempre las recomendaciones de seguridad actualizadas.'], emergency: '171' },
  'Cuba': { visa: { needed: true, info: 'Tarjeta del turista requerida: 25-80 USD. Puede obtenerse en el aeropuerto o consulado.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Peso cubano (CUP). Solo efectivo — tarjetas internacionales no funcionan bien.' }, vaccines: [], tips: ['No lleves tarjetas de bancos americanos.', 'WiFi caro y escaso — tarjetas ETECSA en tiendas oficiales.', 'Casas particulares: mejor opción de alojamiento.'], emergency: '106 (policía) · 104 (ambulancia)' },
  'República Dominicana': { visa: { needed: false, info: 'Sin visado. Tasa turística incluida en muchos vuelos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Peso dominicano (DOP). USD aceptado en zonas turísticas.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['No bebas agua del grifo.', 'Repelente de mosquitos necesario.'], emergency: '911' },
  'Costa Rica': { visa: { needed: false, info: 'Sin visado hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Colón (CRC). El USD también es aceptado.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Alquila coche 4x4 para zonas remotas.', 'Temporada seca: diciembre-abril.'], emergency: '911' },
  'Guatemala': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Quetzal (GTQ). Efectivo necesario.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Antigua muy segura y bonita.', 'No bebas agua del grifo.'], emergency: '110 (policía) · 122 (ambulancia)' },
  'Honduras': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Lempira (HNL). Efectivo principalmente.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Islas de la Bahía: excelente buceo.'], emergency: '911' },
  'El Salvador': { visa: { needed: false, info: 'Sin visado.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Dólar (USD) y Bitcoin (BTC) — legal tender oficial.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Consulta recomendaciones de seguridad.'], emergency: '911' },
  'Nicaragua': { visa: { needed: false, info: 'Sin visado para europeos. Tasa de ingreso: 10 USD.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Córdoba (NIO). Efectivo principalmente.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Granada y León son ciudades coloniales preciosas.'], emergency: '118 (policía) · 128 (ambulancia)' },
  'Panamá': { visa: { needed: false, info: 'Sin visado para europeos y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Adaptador necesario.' }, currency: { info: 'Dólar (USD) — Panamá usa el dólar americano.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada (zonas selváticas)' }], tips: ['El Canal de Panamá es imprescindible.', 'Casco Viejo es el barrio más bonito de Ciudad de Panamá.'], emergency: '911' },
  'Puerto Rico': { visa: { needed: false, info: 'Es territorio de EEUU — mismas reglas. ESTA para europeos.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Clavijas americanas. Europeos necesitan adaptador.' }, currency: { info: 'Dólar (USD).' }, vaccines: [], tips: ['Es como estar en EEUU pero con sabor caribeño.'], emergency: '911' },

  // OCEANÍA
  'Australia': { visa: { needed: true, info: 'ETA: 20 AUD en immi.homeaffairs.gov.au.' }, adapter: { needed: true, type: 'Tipo I', info: 'Clavillas en ángulo. Adaptador necesario.' }, currency: { info: 'Dólar australiano (AUD). Tarjeta aceptada en prácticamente todo.' }, vaccines: [], tips: ['Sol muy intenso — protector FPS 50+ imprescindible.', 'Conducción por la izquierda.', 'Vuelos internos para cubrir distancias enormes.'], emergency: '000' },
  'Nueva Zelanda': { visa: { needed: true, info: 'NZeTA: 23 NZD en immigration.govt.nz.' }, adapter: { needed: true, type: 'Tipo I', info: 'Mismo que Australia. Adaptador necesario.' }, currency: { info: 'Dólar neozelandés (NZD). Tarjeta aceptada en todo.' }, vaccines: [], tips: ['Campervan es la mejor forma de viajar.', 'Temporada alta: diciembre-febrero.'], emergency: '111' },
};

// Plantillas de items de maleta
export const PACKING_TEMPLATES = {
  base: [
    { name: 'Pasaporte', category: 'personal', essential: true },
    { name: 'DNI', category: 'personal', essential: true },
    { name: 'Tarjeta de crédito/débito', category: 'personal', essential: true },
    { name: 'Seguro de viaje', category: 'personal', essential: true },
    { name: 'Copia de reservas impresa', category: 'personal', essential: true },
    { name: 'Efectivo en moneda local', category: 'personal', essential: true },
    { name: 'Cargador del móvil', category: 'tecnologia', essential: true },
    { name: 'Power bank', category: 'tecnologia', essential: false },
    { name: 'Auriculares', category: 'tecnologia', essential: false },
    { name: 'Cepillo y pasta de dientes', category: 'neceser', essential: true },
    { name: 'Desodorante', category: 'neceser', essential: true },
    { name: 'Champú y gel', category: 'neceser', essential: true },
    { name: 'Protector solar', category: 'neceser', essential: true },
    { name: 'Medicación habitual', category: 'medicinas', essential: true },
    { name: 'Ibuprofeno / Paracetamol', category: 'medicinas', essential: true },
    { name: 'Antidiarreico', category: 'medicinas', essential: false },
    { name: 'Tiritas y antiséptico', category: 'medicinas', essential: false },
    { name: 'Ropa interior', category: 'ropa', essential: true },
    { name: 'Calcetines', category: 'ropa', essential: true },
    { name: 'Camisetas', category: 'ropa', essential: true },
    { name: 'Pantalones', category: 'ropa', essential: true },
  ],
  adapter: [{ name: 'Adaptador de enchufe', category: 'tecnologia', essential: true }],
  asia: [
    { name: 'Repelente de mosquitos', category: 'neceser', essential: true },
    { name: 'Antidiarreico extra', category: 'medicinas', essential: true },
    { name: 'Pastillas potabilizadoras', category: 'medicinas', essential: false },
  ],
  japan_extra: [
    { name: 'Tarjeta IC Suica/Pasmo', category: 'personal', essential: true },
    { name: 'Efectivo en yenes', category: 'personal', essential: true },
    { name: 'SIM de datos / Pocket WiFi', category: 'tecnologia', essential: true },
  ],
  usa_extra: [{ name: 'ESTA impresa (confirmación)', category: 'personal', essential: true }],
  cold: [
    { name: 'Abrigo', category: 'ropa', essential: true },
    { name: 'Bufanda y guantes', category: 'ropa', essential: true },
    { name: 'Ropa térmica', category: 'ropa', essential: false },
  ],
  beach: [
    { name: 'Bañador', category: 'ropa', essential: true },
    { name: 'Chanclas', category: 'ropa', essential: true },
    { name: 'Gafas de sol', category: 'neceser', essential: true },
  ],
  // ── América Latina — países que faltaban ──────────────────────────────────
  'Honduras': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días (CA-4).' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos. Adaptador europeo necesario.' }, currency: { info: 'Lempira (HNL). Efectivo en zonas rurales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['Islas de la Bahía: buceo excelente.', 'Copán Ruinas: zona maya imprescindible.'], emergency: '911' },
  'El Salvador': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días (CA-4).' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'USD — moneda oficial. Bitcoin aceptado legalmente.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Surf en El Tunco y El Zonte.', 'País más pequeño de Centroamérica.'], emergency: '911' },
  'Nicaragua': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días (CA-4). Tarjeta turística: 10 USD.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Córdoba (NIO). USD ampliamente aceptado.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Granada es la ciudad más bonita.', 'León: base para ascenso a volcanes.'], emergency: '118 (policía) · 128 (ambulancia)' },
  'Panamá': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'USD — moneda oficial (el Balboa tiene igual valor).' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada para zonas selváticas' }], tips: ['Canal de Panamá: reserva la visita.', 'Casco Viejo es imprescindible.'], emergency: '911' },
  'República Dominicana': { visa: { needed: false, info: 'Sin visado para españoles. Tarjeta turística incluida en el vuelo o 10 USD en aeropuerto.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Peso dominicano (DOP). USD muy aceptado en zonas turísticas.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Agua embotellada siempre.', 'Santo Domingo: primera ciudad colonial de América.'], emergency: '911' },
  'Haití': { visa: { needed: false, info: 'Sin visado hasta 90 días. Consulta el Ministerio de AAEE antes de viajar — situación volátil.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Gourde (HTG). Solo efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['Situación de seguridad inestable — verifica antes de viajar.', 'Solo agua embotellada.'], emergency: '114 (policía)' },
  'Venezuela': { visa: { needed: false, info: 'Sin visado para españoles. Latinoamericanos sin restricción.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Bolívar digital (VES). USD y EUR muy aceptados. Zelle popular.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Verifica situación política y seguridad antes de viajar.', 'Paga en USD para mejores precios.'], emergency: '911' },
  'Ecuador': { visa: { needed: false, info: 'Sin visado para españoles y la mayoría de latinoamericanos hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'USD — moneda oficial.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'requerida para zonas amazónicas' }], tips: ['Galápagos: reserva con mucha antelación.', 'Quito a 2.850m — cuidado con el mal de altura.'], emergency: '911' },
  'Paraguay': { visa: { needed: false, info: 'Sin visado para españoles y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Guaraní (PYG). Solo efectivo en zonas rurales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['Ciudad del Este: zona franca de compras.', 'Asunción: ciudad pequeña y asequible.'], emergency: '911' },
  'Surinam': { visa: { needed: true, info: 'E-visa necesaria: aprox 50 USD. En immigrationsuriname.com.' }, adapter: { needed: false, info: 'Tipo C/F — compatible con enchufes europeos.' }, currency: { info: 'Dólar surinamés (SRD). USD aceptado en Paramaribo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis para zonas selváticas' }], tips: ['Paramaribo: casco colonial UNESCO impresionante.'], emergency: '115 (policía) · 113 (ambulancia)' },
  'Guyana': { visa: { needed: false, info: 'Sin visado para españoles hasta 30 días.' }, adapter: { needed: true, type: 'Tipo A/B/D/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Dólar guyanés (GYD). USD aceptado.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis recomendada' }], tips: ['Ecoturismo increíble en selva amazónica.', 'Georgetown es la capital.'], emergency: '911' },
  'Guyana Francesa': { visa: { needed: false, info: 'Territorio francés — libre circulación para ciudadanos UE. Pasaporte necesario.' }, adapter: { needed: false, info: 'Tipo C/E/F — estándar europeo.' }, currency: { info: 'Euro — territorio francés de ultramar.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis para interior' }], tips: ['Cayena es la capital.', 'Base de lanzamiento de Arianespace en Kourou.'], emergency: '15 (SAMU) · 17 (policía) · 18 (bomberos)' },
  'Belice': { visa: { needed: false, info: 'Sin visado para españoles hasta 30 días.' }, adapter: { needed: true, type: 'Tipo A/B/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Dólar de Belice (BZD). USD ampliamente aceptado (1 USD = 2 BZD).' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['Gran Barrera de Coral del Caribe: segunda del mundo.', 'Inglés es el idioma oficial.'], emergency: '911' },

  // ── Europa — países que faltaban ──────────────────────────────────────────
  'Andorra': { visa: { needed: false, info: 'Sin visado. Territorio aduanero propio — no es UE ni Schengen. Límite de compras duty-free.' }, adapter: { needed: false, info: 'Tipo C/F — igual que España.' }, currency: { info: 'Euro (EUR) aunque no es miembro de la UE.' }, vaccines: [], tips: ['Compras duty-free muy populares.', 'Esquí en invierno: Grandvalira es el mayor resort de los Pirineos.'], emergency: '110 (policía) · 116 (ambulancia)' },
  'Albania': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar — muchos sin visado.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Lek albanés (ALL). Efectivo imprescindible.' }, vaccines: [], tips: ['Costa Riviera albanesa: playas increíbles y aún asequibles.', 'Tirana está cambiando muy rápido.'], emergency: '112 · 129 (policía) · 127 (ambulancia)' },
  'Bosnia y Herzegovina': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. No es Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Marco convertible (BAM). Tipo fijo con el euro. Efectivo en zonas rurales.' }, vaccines: [], tips: ['Mostar: el Stari Most es impresionante.', 'Sarajevo: historia única — la ciudad del asedio.'], emergency: '112 · 122 (policía) · 124 (ambulancia)' },
  'Kosovo': { visa: { needed: false, info: 'Sin visado para españoles. Latinoamericanos: verificar — Kosovo no reconocido por todos los países.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR) aunque no es miembro de la UE.' }, vaccines: [], tips: ['Pristina es pequeña y muy joven.', 'Pecë/Peć: monasterios medievales espectaculares.'], emergency: '112 · 192 (policía)' },
  'Montenegro': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. No es Schengen ni UE.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR) aunque no es miembro de la UE.' }, vaccines: [], tips: ['Kotor: ciudad amurallada UNESCO.', 'Lago Shan: kayak entre montañas.'], emergency: '112 · 122 (policía) · 124 (ambulancia)' },
  'Macedonia del Norte': { visa: { needed: false, info: 'Sin visado para españoles. Latinoamericanos: verificar.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Denar macedonio (MKD). Efectivo muy usado.' }, vaccines: [], tips: ['Ohrid: ciudad lacustre UNESCO.', 'Skopje: arquitectura peculiar y controvertida.'], emergency: '112 · 192 (policía) · 194 (ambulancia)' },
  'Eslovaquia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/E.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['Bratislava: muy visitada desde Viena (1h en tren).', 'Altos Tatras: trekking espectacular.'], emergency: '112 · 158 (policía) · 155 (ambulancia)' },
  'Eslovenia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['Lago Bled: postal perfecta.', 'Ljubljana es pequeña, caminable y encantadora.'], emergency: '112 · 113 (policía)' },
  'Bulgaria': { visa: { needed: false, info: 'UE pero aún no Schengen pleno. Sin visado.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Lev búlgaro (BGN). Tipo fijo con el euro.' }, vaccines: [], tips: ['Sofía es muy asequible.', 'Costa del Mar Negro: playas buenas y baratas.'], emergency: '112 · 166 (policía) · 150 (ambulancia)' },
  'Rumanía': { visa: { needed: false, info: 'UE. Sin visado para españoles.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Leu rumano (RON). No usa euro.' }, vaccines: [], tips: ['Transilvania: sí, existe y es impresionante.', 'Bucarest tiene mucho más que la fama gris.'], emergency: '112 · 955 (policía) · 961 (ambulancia)' },
  'Moldavia': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Leu moldavo (MDL). Efectivo.' }, vaccines: [], tips: ['Chisinau: ciudad tranquila y asequible.', 'Transnistria: región separatista — requiere cuidado.'], emergency: '112 · 902 (policía) · 903 (ambulancia)' },
  'Bielorrusia': { visa: { needed: true, info: 'Los ciudadanos españoles pueden entrar sin visado por el aeropuerto de Minsk hasta 30 días. Latinoamericanos: visado necesario. Verifica situación política.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Rublo bielorruso (BYN). Efectivo.' }, vaccines: [], tips: ['Verifica situación política antes de viajar.', 'Muchas sanciones internacionales vigentes.'], emergency: '112 · 102 (policía) · 103 (ambulancia)' },
  'Ucrania': { visa: { needed: false, info: 'Sin visado para españoles. ATENCIÓN: conflicto armado activo — Ministerio de AAEE desaconseja viajar.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Hryvnia (UAH). Efectivo.' }, vaccines: [], tips: ['NO VIAJAR — conflicto armado activo desde feb 2022.', 'Consulta siempre el Ministerio de AAEE.'], emergency: '112 · 102 (policía) · 103 (ambulancia)' },
  'Letonia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['Riga: arquitectura Art Nouveau única.', 'Jürmala: playa báltica a 30min de Riga.'], emergency: '112 · 110 (policía) · 113 (ambulancia)' },
  'Lituania': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['Vilnius: casco antiguo UNESCO muy bien conservado.', 'Colina de las Cruces en Šiauliai.'], emergency: '112 · 02 (policía) · 03 (ambulancia)' },
  'Estonia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['Tallinn: ciudad medieval más intacta de Europa.', 'País más digital del mundo — casi todo online.'], emergency: '112 · 110 (policía) · 112 (ambulancia)' },
  'Finlandia': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR). País muy caro.' }, vaccines: [], tips: ['Aurora boreal: mejor nov-feb en Laponia.', 'Sauna: experiencia cultural obligatoria.'], emergency: '112' },
  'Malta': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas — como UK. Adaptador necesario.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['La Valeta es la capital más pequeña de la UE.', 'Gozo: más tranquila que Malta principal.'], emergency: '112 · 191 (policía) · 196 (ambulancia)' },
  'Chipre': { visa: { needed: false, info: 'UE. Sin visado para españoles. Norte de Chipre (turco): situación diferente — reconocido solo por Turquía.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Euro (EUR) en el sur. Lira turca en el norte.' }, vaccines: [], tips: ['Cruzar al norte: posible con pasaporte — verifica situación.', 'Paphos: mosaicos romanos impresionantes.'], emergency: '112 · 199 (policía) · 199 (ambulancia)' },
  'Luxemburgo': { visa: { needed: false, info: 'Schengen.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Euro (EUR). País muy caro.' }, vaccines: [], tips: ['Ciudad de Luxemburgo: ciudad capital más bella de Europa para muchos.'], emergency: '112 · 113 (policía) · 112 (ambulancia)' },
  'Liechtenstein': { visa: { needed: false, info: 'Schengen (acuerdo con Suiza).' }, adapter: { needed: true, type: 'Tipo J', info: 'Mismo enchufe que Suiza. Adaptador necesario.' }, currency: { info: 'Franco suizo (CHF).' }, vaccines: [], tips: ['El país más pequeño con frontera con Alemania y Austria.', 'Vaduz: capital con castillo sobre la colina.'], emergency: '112 · 117 (policía) · 144 (ambulancia)' },
  'Mónaco': { visa: { needed: false, info: 'Sin visado — acceso libre desde Francia (Schengen). Pasaporte recomendado.' }, adapter: { needed: false, info: 'Tipo C/E/F — estándar francés.' }, currency: { info: 'Euro (EUR). El lugar más caro del mundo.' }, vaccines: [], tips: ['Monte Carlo Casino: código de vestimenta.', 'Gran Premio de Mónaco: mayo.'], emergency: '17 (policía) · 15 (SAMU) · 18 (bomberos)' },
  'San Marino': { visa: { needed: false, info: 'Sin visado — acceso libre desde Italia.' }, adapter: { needed: false, info: 'Tipo C/F/L — compatible.' }, currency: { info: 'Euro (EUR).' }, vaccines: [], tips: ['El país independiente más antiguo del mundo.', 'Monte Titano: vistas panorámicas.'], emergency: '112 · 0549-888888 (policía)' },
  'Islandia': { visa: { needed: false, info: 'Schengen (no UE).' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Corona islandesa (ISK). Tarjeta aceptada absolutamente en todo.' }, vaccines: [], tips: ['Alquila coche — esencial para el Ring Road.', 'Auroras: sep-mar.', 'Aguas termales: Geysir, Strokkur, Blue Lagoon.'], emergency: '112' },
  'Islas Feroe': { visa: { needed: false, info: 'No es UE ni Schengen pero con pasaporte español sin visado.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Corona feroesa (FOK) y DKK. Tarjeta aceptada en todo.' }, vaccines: [], tips: ['Paisajes más dramáticos de Europa.', 'Torshavn: capital más pequeña de Europa nórdica.'], emergency: '112' },
  'Groenlandia': { visa: { needed: false, info: 'Territorio danés — sin visado para españoles. No es Schengen.' }, adapter: { needed: false, info: 'Tipo C/K — tipo danés.' }, currency: { info: 'Corona danesa (DKK).' }, vaccines: [], tips: ['Ilulissat: fiordos de hielo UNESCO impresionantes.', 'Vuelos solo desde Copenhague o Islandia.'], emergency: '112' },

  // ── África completa ────────────────────────────────────────────────────────
  'Túnez': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar por país.' }, adapter: { needed: false, info: 'Tipo C/E — compatible.' }, currency: { info: 'Dinar tunecino (TND). No se puede sacar del país. Efectivo necesario.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Medinas de Túnez y Sfax: UNESCO.', 'Sousse y Djerba para playa.', 'No bebas agua del grifo.'], emergency: '197 (policía) · 190 (ambulancia)' },
  'Argelia': { visa: { needed: true, info: 'Visado necesario para españoles — tramitar en embajada. Puede ser complejo.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Dinar argelino (DZD). Solo efectivo. No se puede sacar del país.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Sahara argelino: el más auténtico.', 'Turismo aún poco desarrollado.'], emergency: '17 (policía) · 14 (ambulancia)' },
  'Libia': { visa: { needed: true, info: 'Visado muy difícil. NO VIAJAR — conflicto activo.' }, adapter: { needed: false, info: 'Tipo C/D/F/L.' }, currency: { info: 'Dinar libio (LYD).' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Ministerio de AAEE desaconseja totalmente viajar.'], emergency: '1515 (policía)' },
  'Sudán': { visa: { needed: true, info: 'Visado necesario. Situación de seguridad grave — verificar antes.' }, adapter: { needed: false, info: 'Tipo C/D.' }, currency: { info: 'Libra sudanesa (SDG).' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Conflicto armado activo — NO VIAJAR.'], emergency: '999 (policía)' },
  'Etiopía': { visa: { needed: true, info: 'E-visa: 52 USD en evisa.gov.et. Tramitar con antelación.' }, adapter: { needed: true, type: 'Tipo C/D/E/L', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Birr etíope (ETB). Solo efectivo. No se puede sacar moneda.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis para zonas bajas' }], tips: ['Lalibela: iglesias rupestres impresionantes.', 'Addis Abeba a 2.355m — primer día tranquilo.'], emergency: '991 (policía) · 907 (ambulancia)' },
  'Kenia': { visa: { needed: true, info: 'E-visa: 50 USD en evisa.go.ke. Los españoles y mayoría de latinoamericanos la necesitan.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Chelín keniano (KES). M-Pesa muy usado. Efectivo en zonas rurales.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Safari en Masái Mara: jul-oct la gran migración.', 'Nairobi: cuidado con carteristas en zonas concurridas.', 'Repelente de mosquitos cada día.'], emergency: '999 (policía) · 999 (ambulancia)' },
  'Tanzania': { visa: { needed: true, info: 'E-visa: 50 USD en eservices.immigration.go.tz. Españoles y latinoamericanos necesitan.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas.' }, currency: { info: 'Chelín tanzano (TZS). Efectivo necesario. USD aceptado en zonas turísticas.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Serengeti: Great Migration dic-mar (calving) y jul-sep.', 'Kilimanjaro: aclimatación seria — no subestimar.', 'Zanzíbar: playa después del safari.'], emergency: '112 · 112 (policía)' },
  'Uganda': { visa: { needed: true, info: 'E-visa: 50 USD en visas.immigration.go.ug.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas.' }, currency: { info: 'Chelín ugandés (UGX). Efectivo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Gorilas de montaña: permiso 600 USD — reservar con meses de antelación.', 'Bwindi Impenetrable Forest imprescindible.'], emergency: '999 (policía) · 112 (ambulancia)' },
  'Ruanda': { visa: { needed: true, info: 'E-visa: 50 USD en irembo.gov.rw. También visa on arrival.' }, adapter: { needed: true, type: 'Tipo C/J', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Franco ruandés (RWF). Efectivo y tarjeta en Kigali.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis' }], tips: ['Kigali: ciudad más limpia de África.', 'Gorilas: 1.500 USD el permiso — vale cada dólar.'], emergency: '112 · 113 (policía)' },
  'Nigeria': { visa: { needed: true, info: 'Visado necesario — tramitar en embajada. Proceso puede ser lento.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Naira (NGN). Efectivo muy necesario.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Lagos: ciudad caótica pero vibrante.', 'Verifica seguridad por zonas — norte del país evitar.'], emergency: '767 (policía) · 112 (emergencias)' },
  'Ghana': { visa: { needed: true, info: 'E-visa: tramitar en ghanaimmigration.gov.gh.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Cedi (GHS). Efectivo muy necesario fuera de Accra.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Accra: ciudad relativamente segura.', 'Cape Coast Castle: historia del comercio de esclavos impactante.'], emergency: '191 (policía) · 193 (ambulancia)' },
  'Senegal': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar.' }, adapter: { needed: false, info: 'Tipo C/E.' }, currency: { info: 'Franco CFA (XOF). Efectivo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis' }], tips: ['Dakar: animada capital.', 'Isla de Gorée: historia del comercio de esclavos.', 'Casamance: zona más verde y tranquila.'], emergency: '17 (policía) · 15 (ambulancia)' },
  'Mozambique': { visa: { needed: true, info: 'E-visa disponible. Españoles: 50 USD aprox.' }, adapter: { needed: true, type: 'Tipo C/F/M', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Metical (MZN). Efectivo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Islas Quirimbas: paraíso poco conocido.', 'Maputo: la capital más viva de África austral.'], emergency: '119 (policía) · 117 (ambulancia)' },
  'Zambia': { visa: { needed: true, info: 'Visa on arrival o e-visa: 50 USD. KAZA Univisa permite Zambia + Zimbabwe.' }, adapter: { needed: true, type: 'Tipo C/D/G', info: 'Varios tipos.' }, currency: { info: 'Kwacha zambiano (ZMW). USD aceptado en zonas turísticas.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Victoria Falls: mejor en abr-jun cuando lleva más agua.', 'KAZA Univisa para ver las cataratas desde ambos lados.'], emergency: '999 (policía) · 993 (ambulancia)' },
  'Zimbabue': { visa: { needed: true, info: 'Visa on arrival o e-visa: 30-75 USD. KAZA Univisa con Zambia.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Varios tipos.' }, currency: { info: 'USD principalmente. Dólar zimbabuense existe pero inestable.' }, vaccines: [{ name: 'Malaria', priority: 'profilaxis' }, { name: 'Fiebre amarilla', priority: 'recomendada' }], tips: ['Victoria Falls: ver desde el lado zimbabuense (más impactante).', 'Parque Nacional Hwange: elefantes en masa.'], emergency: '999 · 994 (ambulancia)' },
  'Botswana': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar.' }, adapter: { needed: true, type: 'Tipo D/G/M', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Pula (BWP). Tarjeta aceptada en zonas turísticas.' }, vaccines: [{ name: 'Malaria', priority: 'profilaxis para delta del Okavango' }], tips: ['Okavango Delta: safari en mekoro (canoa).', 'Chobe: mayor concentración de elefantes del mundo.'], emergency: '999 (policía) · 997 (ambulancia)' },
  'Namibia': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: verificar.' }, adapter: { needed: true, type: 'Tipo D/M', info: 'Tipo M principalmente. Adaptador necesario.' }, currency: { info: 'Dólar namibio (NAD). Paridad con ZAR — rand también aceptado.' }, vaccines: [], tips: ['Sossusvlei: dunas más altas del mundo.', 'Etosha: safari con fondo de sal blanca.', 'Alquila 4x4 para el interior.'], emergency: '10111 (policía) · 10177 (ambulancia)' },
  'Angola': { visa: { needed: true, info: 'Visado necesario — tramitar en embajada con antelación.' }, adapter: { needed: false, info: 'Tipo C.' }, currency: { info: 'Kwanza (AOA). Efectivo USD muy aceptado.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Luanda: una de las ciudades más caras de África.', 'Playas increíbles al sur.'], emergency: '113 (policía) · 112 (ambulancia)' },
  'Madagascar': { visa: { needed: true, info: 'Visa on arrival: 35 USD para 30 días o 70 USD para 60 días.' }, adapter: { needed: false, info: 'Tipo C/D/E.' }, currency: { info: 'Ariary malgache (MGA). Solo efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }], tips: ['Lémures: solo existen aquí.', 'Baobabs: Avenue des Baobabs al atardecer.', 'Playas en el este: temporada ciclónica dic-mar.'], emergency: '117 (policía) · 119 (ambulancia)' },
  'Mauritania': { visa: { needed: true, info: 'E-visa disponible. Españoles: tramitar con antelación.' }, adapter: { needed: false, info: 'Tipo C.' }, currency: { info: 'Ouguiya mauritana (MRU). Solo efectivo.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida' }, { name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis' }], tips: ['Desierto del Sahara: dunas de Erg Ouane.', 'Banc d'Arguin: aves migratorias UNESCO.'], emergency: '17 (policía)' },

  // ── Asia — países que faltaban ─────────────────────────────────────────────
  'Bután': { visa: { needed: true, info: 'Visado + tasa de desarrollo sostenible: 200 USD/día. Solo via agencia autorizada.' }, adapter: { needed: true, type: 'Tipo C/D/F', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Ngultrum (BTN). Paridad con rupia india.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['El único país que mide la Felicidad Nacional Bruta.', 'Nido del Tigre (Paro Taktsang): excursión imprescindible.'], emergency: '113 (policía) · 112 (ambulancia)' },
  'Myanmar': { visa: { needed: true, info: 'E-visa: 50 USD. Situación política muy inestable — verificar antes.' }, adapter: { needed: true, type: 'Tipo A/C/D/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Kyat (MMK). Solo efectivo en USD nuevos (sin arrugas) o tarjetas locales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Malaria', priority: 'profilaxis para zonas rurales' }], tips: ['Golpe militar 2021 — situación muy inestable.', 'Bagan: templos budistas incomparables.'], emergency: '199 (policía) · 192 (ambulancia)' },
  'Laos': { visa: { needed: true, info: 'E-visa: 35 USD. También visa on arrival: 30-42 USD.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Kip (LAK). Efectivo y USD o THB aceptados.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }], tips: ['Luang Prabang: ciudad más tranquila del sudeste asiático.', 'Vang Vieng: tubing y kayak en el río Nam Song.'], emergency: '191 (policía) · 195 (ambulancia)' },
  'Maldivas': { visa: { needed: false, info: 'Sin visado — 30 días gratuitos a la llegada para todos los pasaportes.' }, adapter: { needed: true, type: 'Tipo D/G/J/K/L', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Rufiyaa (MVR). USD aceptado en resorts. Efectivo local fuera.' }, vaccines: [], tips: ['Resorts: todos incluido generalmente.', 'Snorkel con tiburones ballena en Ari Atoll.', 'Mejor nov-abr (estación seca).'], emergency: '119 (policía) · 102 (ambulancia)' },
  'Timor Oriental': { visa: { needed: false, info: 'Visa on arrival gratuita: 30 días.' }, adapter: { needed: true, type: 'Tipo C/E/F/I', info: 'Varios tipos.' }, currency: { info: 'USD — moneda oficial.' }, vaccines: [{ name: 'Malaria', priority: 'profilaxis' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Uno de los países más jóvenes del mundo.', 'Snorkel excepcional.'], emergency: '112' },
  'Azerbaiyán': { visa: { needed: true, info: 'E-visa: 23 USD en evisa.gov.az. Rápido y sencillo.' }, adapter: { needed: false, info: 'Tipo C/F — compatible.' }, currency: { info: 'Manat azerbaiyano (AZN). Efectivo necesario fuera de Bakú.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Bakú: mezcla de modernidad y ciudad amurallada medieval.', 'Fuegos eternos del Yanar Dag.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Armenia': { visa: { needed: false, info: 'Sin visado para españoles y la mayoría de latinoamericanos hasta 180 días.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Dram armenio (AMD). Efectivo en zonas rurales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Geghard y Garni: monasterios espectaculares.', 'Ereván: muy asequible.', 'No mencionar Nagorno-Karabaj imprudentemente.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Georgia': { visa: { needed: false, info: 'Sin visado para españoles hasta 1 año. Latinoamericanos: muchos sin visado hasta 90-365 días.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Lari georgiano (GEL). Efectivo muy usado.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Tbilisi: una de las ciudades más bonitas de Europa del Este.', 'Vino georgiano: 8.000 años de tradición vinícola.', 'Kazbegi: montañas del Cáucaso impresionantes.'], emergency: '112 · 122 (policía) · 111 (ambulancia)' },
  'Arabia Saudí': { visa: { needed: true, info: 'E-visa turística: 130 USD. Ahora abierto al turismo — antes era cerrado.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas. Adaptador necesario.' }, currency: { info: 'Riyal saudí (SAR). Tarjeta muy aceptada.' }, vaccines: [{ name: 'Meningitis', priority: 'requerida para hajj/umra' }], tips: ['Mujeres pueden viajar solas.', 'Alcohol prohibido.', 'AlUla y Madain Saleh: Petra árabe.'], emergency: '999 (policía) · 997 (ambulancia) · 998 (bomberos)' },
  'Qatar': { visa: { needed: false, info: 'Sin visado para españoles y la mayoría de latinoamericanos. Visa on arrival o Hayya Card.' }, adapter: { needed: true, type: 'Tipo D/G', info: 'Tipo G principalmente. Adaptador necesario.' }, currency: { info: 'Riyal catarí (QAR). Tarjeta ampliamente aceptada.' }, vaccines: [], tips: ['Alcohol solo en hoteles y bares licenciados.', 'Ropa respetuosa en lugares públicos.', 'Calor extremo jun-sep — planifica actividades por las mañanas.'], emergency: '999' },
  'Kuwait': { visa: { needed: true, info: 'E-visa disponible. Españoles: tramitar antes.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas.' }, currency: { info: 'Dinar kuwaití (KWD). La moneda más valiosa del mundo. Tarjeta aceptada.' }, vaccines: [], tips: ['Poco turismo aún — destino auténtico.', 'Souk Al-Mubarakiya: mercado tradicional.'], emergency: '112 (policía) · 112 (ambulancia)' },
  'Omán': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: e-visa 20 USD en evisa.rop.gov.om.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas.' }, currency: { info: 'Riyal omaní (OMR). Tarjeta muy aceptada.' }, vaccines: [], tips: ['Uno de los países más seguros del mundo árabe.', 'Salalah en monzón (jun-sep): verde y único.', 'Wadis: cañones con agua espectaculares.'], emergency: '9999 (policía) · 9999 (ambulancia)' },
  'Bahréin': { visa: { needed: false, info: 'Sin visado para españoles — visa on arrival gratuita. Latinoamericanos: verificar.' }, adapter: { needed: true, type: 'Tipo G', info: 'Tres patillas cuadradas.' }, currency: { info: 'Dinar bareiní (BHD). Tarjeta muy aceptada.' }, vaccines: [], tips: ['Árbol de la Vida: baobab de 400 años en pleno desierto.', 'Manama: cosmopolita y relajada.'], emergency: '999 (policía) · 999 (ambulancia)' },
  'Irak': { visa: { needed: true, info: 'Visado necesario. Zona del Kurdistán iraní más accesible con e-visa.' }, adapter: { needed: false, info: 'Tipo C/D/G.' }, currency: { info: 'Dinar iraquí (IQD). Solo efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Situación de seguridad inestable fuera del Kurdistán.', 'Ur y Babilonia: historia mesopotamia única.'], emergency: '104 (policía)' },
  'Irán': { visa: { needed: true, info: 'Visado necesario — tramitar en embajada. Proceso largo. Algunos pasaportes tienen restricciones.' }, adapter: { needed: false, info: 'Tipo C/F.' }, currency: { info: 'Rial iraní (IRR). Solo efectivo — tarjetas internacionales no funcionan.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Lleva mucho efectivo en USD o EUR.', 'Shiraz, Isfahan y Persépolis: imprescindibles.', 'Mujeres: cubrir cabello en espacios públicos.'], emergency: '110 (policía) · 115 (ambulancia)' },
  'Pakistán': { visa: { needed: true, info: 'E-visa disponible: 75-150 USD. Españoles y muchos latinoamericanos la necesitan.' }, adapter: { needed: true, type: 'Tipo C/D/G/M', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Rupia pakistaní (PKR). Efectivo necesario.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }, { name: 'Tifoidea', priority: 'recomendada' }, { name: 'Rabia', priority: 'considerar' }], tips: ['Norte de Pakistán (Gilgit-Baltistán): montañas más espectaculares del planeta.', 'Karakorum Highway: una de las carreteras más impresionantes del mundo.'], emergency: '15 (policía) · 115 (ambulancia)' },

  // ── Oceanía completa ───────────────────────────────────────────────────────
  'Australia': { visa: { needed: true, info: 'ETA o eVisitor: 20 AUD. Tramitar online antes de viajar. Latinoamericanos: visa ETA 20 USD.' }, adapter: { needed: true, type: 'Tipo I', info: 'Australia y NZ usan tipo I — tres clavijas en triángulo. Adaptador necesario.' }, currency: { info: 'Dólar australiano (AUD). Tarjeta aceptada absolutamente en todo.' }, vaccines: [], tips: ['Distancias enormes — planifica vuelos internos.', 'Protector solar SPF50 obligatorio.', 'Vida marina peligrosa (medusas, tiburones) — haz caso a las señales.'], emergency: '000' },
  'Nueva Zelanda': { visa: { needed: true, info: 'NZeTA: 23 NZD online antes de viajar. Latinoamericanos necesitan visado.' }, adapter: { needed: true, type: 'Tipo I', info: 'Mismo que Australia.' }, currency: { info: 'Dólar neozelandés (NZD). Tarjeta aceptada en todo.' }, vaccines: [], tips: ['Te Anau y Milford Sound: imprescindibles.', 'Alquila campervan — la mejor forma de ver el país.', 'Queenstown: aventura todo el año.'], emergency: '111' },
  'Papúa Nueva Guinea': { visa: { needed: true, info: 'Visa on arrival: 100 PGK aprox. Verificar con embajada.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I — como Australia.' }, currency: { info: 'Kina (PGK). Efectivo imprescindible.' }, vaccines: [{ name: 'Fiebre amarilla', priority: 'requerida si vienes de zona endémica' }, { name: 'Malaria', priority: 'profilaxis obligatoria' }, { name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Una de las mayores diversidades culturales del mundo.', 'Turismo aún poco desarrollado — agencias especializadas necesarias.'], emergency: '000' },
  'Fiyi': { visa: { needed: false, info: 'Sin visado hasta 4 meses para españoles y muchos latinoamericanos.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I — como Australia.' }, currency: { info: 'Dólar fiyiano (FJD). Tarjeta en resorts. Efectivo en zonas rurales.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Arrecifes de coral entre los mejores del mundo.', 'Kava: bebida ceremonial local — buen gesto probarla.'], emergency: '911 · 917 (policía)' },
  'Vanuatu': { visa: { needed: false, info: 'Sin visado hasta 30 días.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I.' }, currency: { info: 'Vatu (VUV). Efectivo.' }, vaccines: [{ name: 'Malaria', priority: 'profilaxis recomendada' }], tips: ['Volcán Yasur en Tanna: uno de los volcanes más accesibles del mundo.', '80 islas, 100+ idiomas.'], emergency: '112' },
  'Samoa': { visa: { needed: false, info: 'Sin visado hasta 60 días.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I.' }, currency: { info: 'Tālā (WST). Efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Cultura Fa'a Samoa muy fuerte.', 'To Sua Ocean Trench: la piscina natural más espectacular del Pacífico.'], emergency: '999 (policía) · 994 (ambulancia)' },
  'Tonga': { visa: { needed: false, info: 'Sin visado hasta 30 días.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I.' }, currency: { info: 'Paʻanga (TOP). Efectivo.' }, vaccines: [{ name: 'Hepatitis A', priority: 'recomendada' }], tips: ['Nadar con ballenas jorobadas: jul-oct.', 'El único reino del Pacífico nunca colonizado.'], emergency: '922 (policía) · 911 (ambulancia)' },
  'Polinesia Francesa': { visa: { needed: false, info: 'Territorio francés — libre circulación para ciudadanos UE. Latinoamericanos: sin visado hasta 90 días.' }, adapter: { needed: false, info: 'Tipo E/F — estándar francés.' }, currency: { info: 'Franco pacífico (XPF). Tarjeta aceptada en Tahití y Bora Bora.' }, vaccines: [], tips: ['Bora Bora: precio altísimo — uno de los destinos más caros del mundo.', 'Moorea: más asequible que Bora Bora y igual de bonita.', 'Snorkel con tiburones es normal y seguro.'], emergency: '17 (policía) · 15 (SAMU)' },


  // ── Países adicionales completando cobertura mundial ──────────────────────
  'Jamaica': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: sin visado hasta 30 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos. Adaptador europeo necesario.' }, currency: { info: 'Dólar jamaicano (JMD). USD muy aceptado en zonas turísticas.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Kingston: cuidado con carteristas.', 'Montego Bay y Negril: playas increíbles.'], emergency: '119' },
  'Barbados': { visa: { needed: false, info: 'Sin visado para españoles hasta 180 días. Latinoamericanos: sin visado hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Dólar de Barbados (BBD). USD aceptado.' }, vaccines: [], tips: ['Bridgetown: capital más antigua del Caribe anglófono.', 'Snorkel excepcional.'], emergency: '211 (policía) · 511 (ambulancia)' },
  'Trinidad y Tobago': { visa: { needed: false, info: 'Sin visado para españoles hasta 90 días. Latinoamericanos: sin visado hasta 90 días.' }, adapter: { needed: true, type: 'Tipo A/B', info: 'Enchufes americanos.' }, currency: { info: 'Dólar de Trinidad y Tobago (TTD). USD aceptado.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Carnaval de Trinidad: febrero — uno de los mejores del Caribe.', 'Tobago: naturaleza increíble y playas tranquilas.'], emergency: '999' },
  'Belice': { visa: { needed: false, info: 'Sin visado hasta 30 días para españoles y la mayoría de latinoamericanos.' }, adapter: { needed: true, type: 'Tipo A/B/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Dólar de Belice (BZD). USD aceptado (1 USD = 2 BZD fijo).' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}, {name: 'Fiebre amarilla', priority: 'recomendada'}], tips: ['Gran Barrera de Coral del Caribe: segunda más grande del mundo.', 'Inglés es el idioma oficial — fácil para anglófonos.'], emergency: '911' },
  'Georgia': { visa: { needed: false, info: 'Sin visado hasta 365 días para españoles y la mayoría de latinoamericanos. Una de las políticas más abiertas del mundo.' }, adapter: { needed: false, info: 'Compatible con enchufes europeos.' }, currency: { info: 'Lari georgiano (GEL). Efectivo muy usado.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Tbilisi: ciudad encantadora con arquitectura única.', 'Vino georgiano: 8.000 años de tradición vinícola.', 'Kazbegi: montañas del Cáucaso impresionantes.'], emergency: '112 · 122 (policía) · 111 (ambulancia)' },
  'Armenia': { visa: { needed: false, info: 'Sin visado hasta 180 días para españoles y latinoamericanos.' }, adapter: { needed: false, info: 'Compatible.' }, currency: { info: 'Dram armenio (AMD). Efectivo en zonas rurales.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Geghard y Garni: monasterios espectaculares.', 'Ereván: muy asequible.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Azerbaiyán': { visa: { needed: true, info: 'E-visa: 23 USD en evisa.gov.az. Trámite sencillo — en 3 días suele estar lista.' }, adapter: { needed: false, info: 'Compatible.' }, currency: { info: 'Manat azerbaiyano (AZN). Efectivo necesario fuera de Bakú.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Bakú: mezcla de ciudad amurallada medieval y rascacielos modernos.', 'Fuegos eternos del Yanar Dag: fenómeno natural único.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Uzbekistán': { visa: { needed: false, info: 'Sin visado hasta 30 días para españoles y latinoamericanos.' }, adapter: { needed: false, info: 'Compatible.' }, currency: { info: 'Som uzbeko (UZS). Efectivo imprescindible — cajeros escasos fuera de Taskent.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}, {name: 'Tifoidea', priority: 'recomendada'}], tips: ['Samarcanda: la ciudad de Tamerlán — impresionante.', 'Bujará: la ciudad más medieval de Asia Central.', 'La Ruta de la Seda en estado puro.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Kazajistán': { visa: { needed: false, info: 'Sin visado hasta 30 días para españoles y latinoamericanos.' }, adapter: { needed: false, info: 'Compatible.' }, currency: { info: 'Tenge kazajo (KZT). Efectivo muy necesario fuera de Almaty y Astana.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Astana (Nur-Sultan): una de las capitales más futuristas del mundo.', 'Almaty: ciudad más vibrante y cultural.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Mongolia': { visa: { needed: false, info: 'Sin visado hasta 30 días para españoles y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo C/E', info: 'Varios tipos. Adaptador universal recomendado.' }, currency: { info: 'Tögrög mongol (MNT). Efectivo imprescindible.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Desierto del Gobi: dunas, dinosaurios y camellos.', 'Naadam: festival nacional en julio — lucha, tiro con arco y equitación.', 'Familia nómada: experiencia auténtica en ger.'], emergency: '102 (policía) · 103 (ambulancia)' },
  'Myanmar': { visa: { needed: true, info: 'E-visa: 50 USD. Situación política muy inestable — verificar siempre antes de viajar.' }, adapter: { needed: true, type: 'Tipo A/C/D/G', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Kyat (MMK). Solo efectivo en billetes USD nuevos (sin arrugas) o tarjetas locales. Las tarjetas internacionales no funcionan bien.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}, {name: 'Malaria', priority: 'profilaxis para zonas rurales'}], tips: ['Golpe militar 2021 — situación muy inestable.', 'Bagan: más de 2.000 templos budistas — espectacular.', 'Inle Lake: pueblo sobre el agua único.'], emergency: '199 (policía) · 192 (ambulancia)' },
  'Laos': { visa: { needed: true, info: 'E-visa: 35 USD. También visa on arrival en puntos fronterizos principales: 30-42 USD.' }, adapter: { needed: true, type: 'Tipo A/B/C', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Kip (LAK). Efectivo y USD o baht tailandés aceptados. 1€ ≈ 22.000 LAK.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}, {name: 'Tifoidea', priority: 'recomendada'}], tips: ['Luang Prabang: ciudad más tranquila y espiritual del Sudeste Asiático.', 'Vang Vieng: tubing y kayak en el río Nam Song.', 'Si Phan Don: 4.000 islas y las cataratas Khone Phapheng.'], emergency: '191 (policía) · 195 (ambulancia)' },
  'Maldivas': { visa: { needed: false, info: 'Sin visado — 30 días gratuitos a la llegada para todos los pasaportes del mundo.' }, adapter: { needed: true, type: 'Tipo D/G/J/K/L', info: 'Varios tipos. Adaptador universal.' }, currency: { info: 'Rufiyaa maldiva (MVR). USD aceptado en todos los resorts. Efectivo local fuera de los resorts.' }, vaccines: [], tips: ['Resorts: todos incluido generalmente.', 'Snorkel con tiburones ballena en Ari Atoll.', 'Mejor nov-abr (estación seca).', 'Presupuesto: puede ser muy caro — busca guesthouses en islas locales para reducir coste.'], emergency: '119 (policía) · 102 (ambulancia)' },
  'Bután': { visa: { needed: true, info: 'Visado + tasa de desarrollo sostenible: 100 USD/día (rebajado desde 200 en 2024). Solo via agencia autorizada — no hay turismo independiente.' }, adapter: { needed: true, type: 'Tipo C/D/F', info: 'Varios tipos.' }, currency: { info: 'Ngultrum butanés (BTN). Paridad con rupia india. Efectivo.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['El país que mide la Felicidad Nacional Bruta.', 'Nido del Tigre (Paro Taktsang): excursión icónica.', 'Solo para grupos organizados con guía licenciado.'], emergency: '113 (policía) · 112 (ambulancia)' },
  'Samoa': { visa: { needed: false, info: 'Sin visado hasta 60 días para la mayoría de pasaportes incluyendo españoles y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I como Australia. Adaptador necesario.' }, currency: { info: 'Tālā samoano (WST). Efectivo.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Cultura Fa'a Samoa: respetar las tradiciones locales.', 'To Sua Ocean Trench: la piscina natural más espectacular del Pacífico.', 'Aguas cristalinas y arrecifes de coral.'], emergency: '999 (policía) · 994 (ambulancia)' },
  'Tonga': { visa: { needed: false, info: 'Sin visado hasta 30 días para la mayoría de pasaportes.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I.' }, currency: { info: 'Paʻanga tongano (TOP). Efectivo.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Nadar con ballenas jorobadas: jul-oct — experiencia única en el mundo.', 'El único reino polinésico nunca colonizado.', '175 islas de las cuales 36 habitadas.'], emergency: '922 (policía) · 911 (ambulancia)' },
  'Fiyi': { visa: { needed: false, info: 'Sin visado hasta 120 días para la mayoría de pasaportes incluyendo españoles y latinoamericanos.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I como Australia.' }, currency: { info: 'Dólar fiyiano (FJD). Tarjeta en resorts y ciudades. Efectivo en zonas rurales e islas remotas.' }, vaccines: [{name: 'Hepatitis A', priority: 'recomendada'}], tips: ['Arrecifes de coral entre los mejores del mundo.', 'Kava: bebida ceremonial — buen gesto probarla al llegar a una aldea.', 'Yasawa Islands: la Fiyi auténtica y menos turística.'], emergency: '911 · 917 (policía)' },
  'Vanuatu': { visa: { needed: false, info: 'Sin visado hasta 30 días para la mayoría de pasaportes.' }, adapter: { needed: true, type: 'Tipo I', info: 'Tipo I.' }, currency: { info: 'Vatu (VUV). Efectivo.' }, vaccines: [{name: 'Malaria', priority: 'profilaxis recomendada'}], tips: ['Volcán Yasur en Tanna: uno de los volcanes más accesibles y activos del mundo.', '80 islas y más de 100 idiomas diferentes.', 'Snorkel en Million Dollar Point: barcos de guerra de la II Guerra Mundial.'], emergency: '112' },
  'Polinesia Francesa': { visa: { needed: false, info: 'Territorio francés — libre circulación UE. Latinoamericanos: sin visado hasta 90 días.' }, adapter: { needed: false, info: 'Estándar francés.' }, currency: { info: 'Franco Pacífico CFP (XPF). Tarjeta aceptada en Tahití y Bora Bora. Efectivo en islas remotas.' }, vaccines: [], tips: ['Bora Bora: uno de los destinos más caros del mundo.', 'Moorea: más asequible que Bora Bora e igual de bonita.', 'Fakarava: snorkel con tiburones en paso de arrecife — impresionante.'], emergency: '17 (policía) · 15 (SAMU)' },

};

export function getSmartPackingList(country) {
  const req = COUNTRY_REQUIREMENTS[country] || null;
  const items = [...PACKING_TEMPLATES.base];
  if (req?.adapter?.needed) items.push(...PACKING_TEMPLATES.adapter);
  const asiaCountries = ['Japón', 'Tailandia', 'Vietnam', 'India', 'Indonesia', 'China', 'Corea del Sur', 'Camboya', 'Filipinas', 'Nepal', 'Sri Lanka', 'Singapur'];
  if (asiaCountries.includes(country)) items.push(...PACKING_TEMPLATES.asia);
  if (country === 'Japón') items.push(...PACKING_TEMPLATES.japan_extra);
  if (country === 'Estados Unidos' || country === 'Canadá') items.push(...PACKING_TEMPLATES.usa_extra);
  const seen = new Set();
  return { items: items.filter(i => { if (seen.has(i.name)) return false; seen.add(i.name); return true; }), requirements: req };
}